""""""""""""""""""""""""""""""""""""""""""""""""""
" Pathogen
""""""""""""""""""""""""""""""""""""""""""""""""""
execute pathogen#infect()
filetype plugin indent on

""""""""""""""""""""""""""""""""""""""""""""""""""
" General
""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible
set modelines=0

""""""""""""""""""""""""""""""""""""""""""""""""""
" Appearance
""""""""""""""""""""""""""""""""""""""""""""""""""
syntax on                        " syntax highlighting
set t_Co=256                     " 256 color support
colorscheme monokai              " pretty colors

set noerrorbells
set novisualbell

""""""""""""""""""""""""""""""""""""""""""""""""""
" Tabs
""""""""""""""""""""""""""""""""""""""""""""""""""
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent

""""""""""""""""""""""""""""""""""""""""""""""""""
" Widgets and sanity
""""""""""""""""""""""""""""""""""""""""""""""""""
set backspace=eol,start,indent
set cursorline                   " highlight current line
set relativenumber               " show line numbers relative to current line
set ruler                        " show current line and column
set showcmd                      " show the current command
set showmode                     " show the current mode

set noswapfile

""""""""""""""""""""""""""""""""""""""""""""""""""
" Search
""""""""""""""""""""""""""""""""""""""""""""""""""
nnoremap / /\v
vnoremap / /\v

set ignorecase
set smartcase

set gdefault

set incsearch                    " search as characters are entered
set showmatch
set hlsearch                     " highlight matches

""""""""""""""""""""""""""""""""""""""""""""""""""
" Long lines
""""""""""""""""""""""""""""""""""""""""""""""""""
set wrap
set textwidth=79
" TODO: formatoptions
set colorcolumn=81

""""""""""""""""""""""""""""""""""""""""""""""""""
" Remapping
""""""""""""""""""""""""""""""""""""""""""""""""""
let mapleader = ","              " more convenient than \
" fast write
nnoremap <Leader>w :update<CR>

nnoremap <c-h> <c-W>h
nnoremap <c-j> <c-W>j
nnoremap <c-k> <c-W>k
nnoremap <c-l> <c-W>l

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugins
""""""""""""""""""""""""""""""""""""""""""""""""""
" Ctrl P
nnoremap <Leader>t :CtrlP<CR>

let g:startify_bookmarks = ['~/.vim/vimrc']

let g:startify_custom_footer =
      \ ['', "   Vim is charityware. Please read ':help uganda'.", '']
